[rospy.client][INFO] 2017-06-12 14:06:52,182: init_node, name[/move_sandbox_items], pid[16559]
[xmlrpc][INFO] 2017-06-12 14:06:52,183: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2017-06-12 14:06:52,183: Started XML-RPC server [http://sandtray-hrilab:46658/]
[rospy.init][INFO] 2017-06-12 14:06:52,183: ROS Slave URI: [http://sandtray-hrilab:46658/]
[rospy.impl.masterslave][INFO] 2017-06-12 14:06:52,183: _ready: http://sandtray-hrilab:46658/
[rospy.registration][INFO] 2017-06-12 14:06:52,184: Registering with master node http://localhost:11311
[xmlrpc][INFO] 2017-06-12 14:06:52,184: xml rpc node: starting XML-RPC server
[rospy.init][INFO] 2017-06-12 14:06:52,284: registered with master
[rospy.rosout][INFO] 2017-06-12 14:06:52,284: initializing /rosout core topic
[rospy.rosout][INFO] 2017-06-12 14:06:52,286: connected to core topic /rosout
[rospy.simtime][INFO] 2017-06-12 14:06:52,288: /use_sim_time is not set, will not subscribe to simulated time [/clock] topic
[rospy.internal][INFO] 2017-06-12 14:06:52,302: topic[/tf] adding connection to [http://sandtray-hrilab:34760/], count 0
[rospy.internal][INFO] 2017-06-12 14:06:52,303: topic[/tf] adding connection to [http://sandtray-hrilab:36072/], count 0
[rospy.internal][INFO] 2017-06-12 14:06:52,304: topic[/tf] adding connection to [http://sandtray-hrilab:45963/], count 1
[rospy.internal][INFO] 2017-06-12 14:06:52,306: topic[/tf] adding connection to [http://sandtray-hrilab:37909/], count 3
[rospy.internal][INFO] 2017-06-12 14:06:52,308: topic[/tf] adding connection to [http://sandtray-hrilab:33542/], count 4
[rospy.internal][INFO] 2017-06-12 14:06:52,515: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2017-06-12 14:06:52,546: topic[/poses] adding connection to [/sandtray], count 0
[rospy.internal][WARNING] 2017-06-12 14:08:16,156: Unknown error initiating TCP/IP socket to sandtray-hrilab:48757 (http://sandtray-hrilab:36072/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-12 14:08:16,156: topic[/tf] removing connection to http://sandtray-hrilab:36072/
[rospy.internal][INFO] 2017-06-12 14:10:35,181: topic[/tf] adding connection to [http://sandtray-hrilab:44125/], count 4
[rospy.internal][INFO] 2017-06-12 14:10:36,146: topic[/tf] adding connection to [http://sandtray-hrilab:39308/], count 5
[rospy.internal][WARNING] 2017-06-12 14:29:15,697: Unknown error initiating TCP/IP socket to sandtray-hrilab:42245 (http://sandtray-hrilab:44125/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-12 14:29:15,697: topic[/tf] removing connection to http://sandtray-hrilab:44125/
[rospy.internal][WARNING] 2017-06-12 14:29:15,698: Unknown error initiating TCP/IP socket to sandtray-hrilab:51464 (http://sandtray-hrilab:39308/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 557, in connect
    self.read_header()
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 650, in read_header
    self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosgraph/network.py", line 362, in read_ros_handshake_header
    d = sock.recv(buff_size)
error: [Errno 104] Connection reset by peer

[rospy.internal][INFO] 2017-06-12 14:29:15,698: topic[/tf] removing connection to http://sandtray-hrilab:39308/
[rospy.core][INFO] 2017-06-12 14:37:45,396: signal_shutdown [signal-15]
[rospy.internal][WARNING] 2017-06-12 14:37:45,397: Unknown error initiating TCP/IP socket to sandtray-hrilab:43483 (http://sandtray-hrilab:45963/): Traceback (most recent call last):
  File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 555, in connect
    self.socket.connect((dest_addr, dest_port))
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
error: [Errno 111] Connection refused

[rospy.internal][INFO] 2017-06-12 14:37:45,397: topic[/tf] removing connection to http://sandtray-hrilab:45963/
[rospy.internal][INFO] 2017-06-12 14:37:45,403: topic[/poses] removing connection to /sandtray
[rospy.internal][INFO] 2017-06-12 14:37:45,403: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2017-06-12 14:37:45,404: topic[/tf] removing connection to http://sandtray-hrilab:34760/
[rospy.internal][INFO] 2017-06-12 14:37:45,404: topic[/tf] removing connection to http://sandtray-hrilab:37909/
[rospy.internal][INFO] 2017-06-12 14:37:45,404: topic[/tf] removing connection to http://sandtray-hrilab:33542/
[rospy.impl.masterslave][INFO] 2017-06-12 14:37:45,404: signal-15
[rospy.core][INFO] 2017-06-12 14:37:46,015: signal_shutdown [signal-2]
[rospy.core][INFO] 2017-06-12 14:37:46,015: signal_shutdown [atexit]
